kind: Deployment
apiVersion: apps/v1
metadata:
    name: catalog
    labels:
        version: v1
spec:
    replicas: 2
    selector:
        matchLabels:
            app: catalog
            version: v1
    template:
        metadata:
            labels:
                app: catalog
                version: v1
        spec:
            volumes:
              - name: vol-15927317327
                configMap:
                    name: catalog-configmap
                    items:
                      - key: fdb.cluster
                        path: fdb.cluster
            containers:
              - name: containers-catalog-test
                image: dongsishan/catalog:v1
                volumeMounts: 
                  - name: vol-15927317327
                    readOnly: true
                    mountPath: /etc/foundationdb


